# Generated by Django 5.2.7 on 2025-11-14 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Marshrut nomi')),
                ('start_point', models.CharField(max_length=150, verbose_name='Boshlanish nuqtasi')),
                ('end_point', models.CharField(max_length=150, verbose_name='Tugash nuqtasi')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Masofa (km)')),
                ('estimated_time', models.DurationField(verbose_name='Taxminiy vaqt')),
            ],
            options={
                'verbose_name': 'Marshrut',
                'verbose_name_plural': 'Marshrutlar',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Davlat raqami')),
                ('vehicle_type', models.CharField(choices=[('bus', 'Avtobus'), ('minibus', 'Mikroavtobus'), ('taxi', 'Taksi'), ('train', 'Poyezd')], max_length=20, verbose_name='Transport turi')),
                ('capacity', models.PositiveIntegerField(verbose_name='O‘rinlar soni')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Haydovchi ismi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Transport vositasi',
                'verbose_name_plural': 'Transport vositalari',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='O‘rindiq raqami')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Sotib olingan vaqt')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilganmi')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/', verbose_name='QR-kod')),
                ('ticket_code', models.CharField(max_length=12, unique=True, verbose_name='Chipta kodi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Chipta',
                'verbose_name_plural': 'Chiptalar',
            },
        ),
        migrations.CreateModel(
            name='TicketValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_at', models.DateTimeField(auto_now_add=True, verbose_name='Tekshirilgan vaqt')),
                ('validator', models.CharField(max_length=100, verbose_name='Tekshiruvchi (masalan, haydovchi)')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Haqiqiyligi')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ticket', verbose_name='Chipta')),
            ],
            options={
                'verbose_name': 'Tekshiruv',
                'verbose_name_plural': 'Tekshiruvlar',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Jo‘nash vaqti')),
                ('arrival_time', models.DateTimeField(verbose_name='Yetib borish vaqti')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Narxi (so‘m)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route', verbose_name='Marshrut')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle', verbose_name='Transport')),
            ],
            options={
                'verbose_name': 'Reyss',
                'verbose_name_plural': 'Reysslar',
                'ordering': ['departure_time'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trip', verbose_name='Reyss'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('trip', 'seat_number')},
        ),
    ]
